package com.ams.enums;

public enum NotificationType {
    ASSET_EXPIRING_WARRANTY,
    ASSET_ASSIGNED,
    ASSET_RETURNED,
    MAINTENANCE_DUE,
    APPROVAL_REQUIRED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    SYSTEM,
    REPAIR_SUBMITTED,
    REPAIR_COMPLETED
}
